const assert=require('node:assert/strict');
const fs=require('node:fs');
const js=fs.readFileSync('drawing-board-workflow-v2.js','utf8');
const css=fs.readFileSync('drawing-board-workflow-v2.css','utf8');
const app=fs.readFileSync('tarot-app.js','utf8');
assert.match(js,/Astrological Tarot Reading/);
assert.match(js,/\+ Compare a second sky/);
assert.match(js,/data-remove-astrology-sky="B"/);
assert.match(js,/Connected · /);
assert.match(js,/relphiConnectSky/);
assert.match(js,/RELPHI_ASTROLOGICAL_TAROT_CONTEXT/);
assert.match(js,/options\.textContent='Crafted'/);
assert.match(js,/boardTab\.textContent='Free'/);
assert.match(js,/const previousScrollTop=preserveScroll&&previousBody \? previousBody\.scrollTop : null/);
assert.match(js,/nextBody\.scrollTop=previousScrollTop/);
assert.match(css,/\.relphi-astrology-surface/);
assert.match(app,/drawing-board-mode-switch/);
assert.match(app,/role="radiogroup" aria-label="Drawing mode"/);
assert.match(app,/>Mode:<\/strong>/);
assert.doesNotMatch(app,/drawing-board-mode-tabs/);
console.log('Crafted Draw exposes the Astrological Tarot Reading setup and preserves pack-selector scroll position.');

assert.match(js,/function astrologyAnalyzeResolved/);
assert.match(js,/function astrologyCardHits/);
assert.match(js,/function astrologyPatterns/);
assert.match(js,/function astrologyQuestionSuggestions/);
assert.match(js,/Suggested questions/);
assert.doesNotMatch(js,/Each sky is a disposable reading copy/);
assert.doesNotMatch(js,/Zodiacal Majors locate houses/);

assert.match(app,/relphi:sky-calculated/);
assert.doesNotMatch(js,/<strong>Sky '\+slot\+'<\/strong>/);
assert.match(js,/Use '\+\(count>1\?'These Skies':'This Sky'\)/);
assert.doesNotMatch(js,/Connect Sky A or Sky A \+ Sky B/);
