const assert=require('node:assert/strict');
const fs=require('node:fs');
const js=fs.readFileSync('drawing-board-workflow-v2.js','utf8');
const css=fs.readFileSync('drawing-board-workflow-v2.css','utf8');
const app=fs.readFileSync('tarot-app.js','utf8');
assert.match(js,/Astrological Tarot Reading/);
assert.match(js,/Sky A \+ Sky B/);
assert.match(js,/relphiConnectSky/);
assert.match(js,/relphi:request-sky-connection/);
assert.match(js,/options\.textContent='Crafted'/);
assert.match(js,/boardTab\.textContent='Free'/);
assert.match(js,/const scrollTop=body\?\.scrollTop\|\|0/);
assert.match(css,/\.relphi-astrology-surface/);
assert.match(app,/drawing-board-mode-switch/);
assert.match(app,/role="radiogroup" aria-label="Drawing mode"/);
assert.match(app,/>Mode:<\/strong>/);
assert.doesNotMatch(app,/drawing-board-mode-tabs/);
console.log('Crafted Draw exposes the Astrological Tarot Reading setup and preserves pack-selector scroll position.');
