import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import test from 'node:test';

const require=createRequire(import.meta.url),{chromium}=require('playwright');
const root=path.resolve(import.meta.dirname,'..');
let server,browser,page,origin;

test.before(async()=>{server=http.createServer((req,res)=>{const url=new URL(req.url,'http://x'),file=path.join(root,decodeURIComponent(url.pathname));if(!file.startsWith(root)){res.writeHead(403).end();return;}try{const body=fs.readFileSync(file);res.setHeader('content-type',file.endsWith('.mjs')?'text/javascript':file.endsWith('.json')?'application/json':file.endsWith('.svg')?'image/svg+xml':'text/html');res.end(body);}catch{res.writeHead(404).end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin=`http://127.0.0.1:${server.address().port}`;browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||undefined});page=await browser.newPage();await page.goto(`${origin}/review/canonical-glyph-loader-prototype.html`);await page.evaluate(async()=>{window.loaderModule=await import('./canonical-glyph-loader-prototype.mjs');});});
test.after(async()=>{await browser?.close();await new Promise(resolve=>server?.close(resolve));});
const run=(identity,state,mode='normal')=>page.evaluate(async({identity,state,mode})=>{const base='../assets/canonical-glyphs/v1/manifest.json';let fetchImpl=fetch;if(mode!=='normal')fetchImpl=async url=>{const value=String(url);if(mode==='malformed-manifest'&&value.endsWith('manifest.json'))return new Response('{}',{status:200,headers:{'content-type':'application/json'}});if(mode==='missing-master'&&value.includes('mercury.svg'))return new Response('',{status:404});if(mode==='missing-overlay'&&value.includes('circled.svg'))return new Response('',{status:404});const response=await fetch(url);if(mode==='hash-mismatch'&&value.includes('mercury.svg'))return new Response((await response.text())+' ',{status:200});return response;};const loader=window.loaderModule.createCanonicalGlyphLoader({manifestUrl:base,fetchImpl});try{const node=await loader.loadCanonicalGlyph(identity,{state});return{ok:true,html:node.outerHTML,children:node.children.length,viewBoxes:[...node.querySelectorAll('svg')].map(x=>x.getAttribute('viewBox')),transforms:node.querySelectorAll('[transform]').length,text:node.textContent};}catch(error){return{ok:false,code:error.code,message:error.message};}},{identity,state,mode});

test('successful Plain loading is complete and deterministic',async()=>{const [a,b]=await Promise.all([run('mercury','plain'),run('mercury','plain')]);assert.equal(a.ok,true);assert.equal(a.children,1);assert.deepEqual(a.viewBoxes,['0 0 100 100']);assert.equal(a.html,b.html);});
test('successful Circled composition uses two static preserved-viewBox layers',async()=>{const r=await run('mercury','circled');assert.equal(r.ok,true);assert.equal(r.children,2);assert.deepEqual(r.viewBoxes,['0 0 100 100','0 0 100 100']);assert.equal(r.transforms,0);});
for(const [label,identity,state,mode,code] of [['unavailable identity','chiron','plain','normal','MASTER_UNAVAILABLE'],['unavailable ruler','mercury','day-ruler','normal','OVERLAY_UNAVAILABLE'],['unknown identity','not-real','plain','normal','UNKNOWN_IDENTITY'],['unknown state','mercury','invented','normal','UNKNOWN_STATE'],['missing asset','mercury','plain','missing-master','MASTER_LOAD_FAILED'],['hash mismatch','mercury','plain','hash-mismatch','HASH_MISMATCH'],['malformed manifest','mercury','plain','malformed-manifest','MALFORMED_MANIFEST']])test(`${label} fails closed`,async()=>assert.equal((await run(identity,state,mode)).code,code));
test('overlay failure returns no partial glyph',async()=>{const r=await run('mercury','circled','missing-overlay');assert.equal(r.ok,false);assert.equal(r.code,'OVERLAY_LOAD_FAILED');assert.equal(await page.locator('#stage > *').count(),0);});
test('prototype source contains no fallback or runtime geometry construction',()=>{const source=fs.readFileSync(path.join(root,'review/canonical-glyph-loader-prototype.mjs'),'utf8');assert.doesNotMatch(source,/getBBox|createElementNS|<circle|Unicode|textGlyph|createBubble|\bradius\b|\bpadding\b|setAttribute\(['"]transform/);});
test('concurrent requests return completed independent instances',async()=>{const results=await Promise.all(Array.from({length:8},()=>run('venus','circled')));assert.ok(results.every(x=>x.ok&&x.children===2));assert.equal(new Set(results.map(x=>x.html)).size,1);});
