const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const board = read('drawing-board-workflow-v2.js');
const app = read('tarot-app.js');
const css = read('drawing-board-workflow-v2.css');

assert.match(board, /Native board state and rendering remain owned by tarot-app\.js/);
assert.match(app, /function renderShortList\(/);
assert.match(app, /function boardSnapshot\(/);
assert.match(board, /function beginOptionsSession/);
assert.match(board, /baseline:currentSnapshot\(\), draft:draftFromState\(\)/);
assert.match(board, /function applyOptions/);
assert.match(board, /function resetBoardFromOptions/);
assert.match(board, /function draftPrefab/);
assert.match(board, /Save template/);
assert.match(board, /Add position/);
assert.match(board, /Show position stickers/);
assert.match(board, /Reversals/);
assert.match(board, /Repeats/);
assert.match(board, /function zoomExtents/);
assert.match(board, /function installExportArea/);
assert.match(board, /drawing-board-post-export/);
assert.match(board, /stateContentBounds\(snapshot,count\)/);
assert.doesNotMatch(board, /querySelectorAll\([^\n]*card-row-item[^\n]*\)\s*\.map\([^\n]*getBoundingClientRect/);
assert.match(board, /function openFocus/);
assert.match(board, /cloneNode\(true\)/);
assert.match(css, /or-card-layer\.relphi-info-layer/);
assert.match(board, /function navigateFocus/);
assert.doesNotMatch(board, /Complete Reading/);
assert.match(board, /function drawInto/);
assert.match(board, /pendingFocusIndex/);
assert.match(board, /function setBoardOpen/);
assert.match(board, /Open Drawing Board/);
assert.match(board, /Close Drawing Board/);
assert.match(css, /touch-action:pan-x pan-y/);
assert.match(css, /card-row-workspace-toolbar\.relphi-board-controller/);
assert.match(css, /relphi-reading-options-drawer/);
assert.match(css, /relphi-options-commitbar/);
assert.match(css, /relphi-focus-reader/);
assert.match(css, /card-row-workspace-toolbar:not\(\.relphi-board-controller\).*visibility:hidden!important/);
assert.match(css, /relphi-board-export/);
console.log('Drawing Board workflow v2 checks passed.');
