const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const board = read('drawing-board-workflow-v2.js');
const app = read('tarot-app.js');
const css = read('drawing-board-workflow-v2.css');
const tarotPage = read('tarot.html');
const skyPage = read('sky-chart.html');
const hoursPage = read('planetaryhours.html');
const sharedStyle = read('style.css');
const chromeOwner = read('drawing-board-chrome-ownership-v1.js');

assert.match(board, /Native board state and rendering remain owned by tarot-app\.js/);
assert.match(app, /function renderShortList\(/);
assert.match(app, /function boardSnapshot\(/);
assert.match(board, /function beginOptionsSession/);
assert.match(board, /baseline:currentSnapshot\(\), draft:draftFromState\(\)/);
assert.match(board, /function applyOptions/);
assert.match(board, /function ensureBoardChrome/);
assert.match(board, /window\.RelphiDrawingBoardEnsureTopActions = ensureBoardChrome/);
assert.match(board, /relphi-board-commandbar/);
assert.match(board, /relphiBoardSettingsButton/);
assert.match(board, /Clear the cards without changing settings/);
assert.match(board, /Restore default settings/);
assert.match(board, /function renderFreeSettings/);
assert.match(board, /id="relphiFreePack"/);
assert.match(board, /> Labels<\/label>/);
assert.match(board, /> Reversals<\/label>/);
assert.match(board, /> Repeats<\/label>/);
assert.match(board, /function confirmFreeSettings/);
assert.match(board, /function cancelBoardSettings/);
assert.match(board, /boardSetupConfirmed=true/);
assert.match(board, /settingsMode='free'/);
assert.match(board, /settingsMode='crafted'/);
assert.match(board, />Confirm<\/button>/);
assert.match(board, /function keepAstrologyConnectorInView/);
assert.doesNotMatch(board, /Assigned sub-pack/);
assert.doesNotMatch(board, /Suggested sub-pack/);
assert.match(board, /<small>'\+escapeHtml\(packLabel\(q\.pack\)\)\+'<\/small>/);
assert.match(board, /Accepting a generated question also accepts its assigned sub-pack/);
assert.match(board, /data-astrology-own-pack/);
assert.match(board, /Choose sub-pack…/);
assert.match(board, /Choose a sub-pack for your authored question/);
assert.match(board, /pack:ownPack,source:'authored'/);
assert.match(board, /session\.path==='surface'\|\|session\.path==='astro'/);
assert.match(board, /relphi-astrology-bridge-status/);
assert.match(board, /#relphiConnectSky/);
assert.match(board, /body\.scrollTo\(\{top:Math\.max\(0,targetTop\),behavior:'smooth'\}\)/);
assert.match(board, /session\.path==='astro' && !session\.astrologyAnalysis/);
assert.match(board, /requestAnimationFrame\(\(\)=>requestAnimationFrame\(\(\)=>keepAstrologyConnectorInView\(root\)\)\)/);
assert.match(board, /function resetBoardFromOptions/);
assert.match(board, /function draftPrefab/);
assert.match(board, /Save template/);
assert.match(board, /Show position stickers/);
assert.match(board, /const drawSettingsMarkup=\(session\.path==='surface'\|\|session\.path==='astro'\)/);
assert.match(board, /relphi-draw-options--surface/);
assert.match(board, /Each probe uses the sub-pack shown beneath it/);
assert.match(board, /data-surface-select-all/);
assert.match(board, /data-surface-readiness/);
assert.match(board, /relphi-surface-readiness-rail/);
assert.match(board, /data-readiness-step="path"/);
assert.match(board, /<strong>Path<\/strong><small>See What Surfaces<\/small>/);
assert.match(board, /Card source/);
assert.match(board, /Questions/);
assert.match(board, /Ready/);
assert.match(board, /Minimum met/);
assert.match(board, /Ready to begin/);
assert.match(board, /One question is enough to craft the reading/);
assert.match(board, /data-surface-select-all-bottom/);
assert.match(board, /setAllSurfaceChoices/);
assert.match(board, /surfaceReadiness\.classList\.toggle\('is-ready',ready\)/);
assert.match(board, /data-sacred-card-source/);
assert.match(board, /data-sacred-card-source-group/);
assert.match(board, /<legend>Card source<\/legend>/);
assert.match(board, /Digital cards/);
assert.match(board, /Default · Relphi selects each card/);
assert.match(board, /Physical deck/);
assert.match(board, /Choose this only when you will draw the cards yourself/);
assert.match(board, /sacredCardSource:'digital'/);
assert.match(board, /start\.disabled=!count/);
assert.match(board, /if\(!\['digital','physical'\]\.includes\(session\?\.sacredCardSource\)\)session\.sacredCardSource='digital'/);
assert.match(board, /function stampSacredCardSource/);
assert.match(board, /cardSource:session\.sacredCardSource==='physical'\?'physical':'digital'/);
assert.match(board, /Select all '\+SURFACE_DRAW_KEYS\.length/);
assert.match(board, /One probe from every See What Surfaces sub-pack/);
assert.match(board, /surfaceSelectAll\.indeterminate=count>0&&count<SURFACE_DRAW_KEYS\.length/);
assert.match(board, /SURFACE_DRAW_KEYS\.forEach\(kind=>\{session\.surfaceSelected\[kind\]=surfaceSelectAll\.checked;\}\)/);
assert.match(board, /new Set\(SURFACE_INITIAL_PACKS\)\.size !== SURFACE_DRAW_KEYS\.length/);
assert.match(board, /draft\.positionPacks=kinds\.map\(kind=>SURFACE_PACK_BY_KIND\[kind\]\|\|''\)/);
assert.match(board, /Unpack this card/);
assert.match(board, /relphi-focus-art-actions/);
assert.doesNotMatch(board, /relphi-focus-position-actions/);
assert.match(board, /function unpackSurfaceCard/);
assert.match(board, /derivedFromCard/);
assert.match(board, /derivedFromReversed/);
assert.match(board, /pack:'full'/);
assert.match(board, /Current branch complete/);
assert.match(board, /function openSurfaceQuestionComposer/);
assert.match(board, /Choose what to ask next/);
assert.match(board, /Add my own question/);
assert.match(board, /Suggest another question/);
assert.match(board, /function nextSurfaceSuggestion/);
assert.match(board, /function surfacedSuggestionPool/);
assert.match(board, /data-surface-suggest/);
assert.match(board, /Add selected questions/);
assert.match(board, /data-surface-pack/);
assert.match(board, /function surfaceKeywordMarkup/);
assert.match(board, /data-surface-tag-query/);
assert.match(board, /data-surface-tag-choice/);
assert.match(board, /keywordQuery:String\(item\.keywordQuery\|\|''\)/);
assert.match(board, /Choose at least one keyword or tag for every Keywords \/ Tags question/);
assert.match(board, /keywordTags\.join\(keywordMode==='all'\?' \+ ':' \/ '\)/);
assert.match(board, /keywordTags:Array\.isArray\(derived\.keywordTags\)/);
assert.match(board, /snap\.rowSelectedTags=Array\.isArray\(meta\.keywordTags\)/);
assert.match(board, /keywordMatchMode/);
assert.match(board, /data-surface-card-count/);
assert.match(board, /data-surface-link/);
assert.match(board, /function surfaceComposerAdvancedSummary/);
assert.match(board, /relphi-surface-composer-advanced/);
assert.match(board, /data-surface-advanced/);
assert.match(board, /<summary><strong>Advanced<\/strong>/);
assert.match(board, /advancedOpen:false/);
assert.match(board, /function expandSurfaceEntries/);
assert.match(board, /questionCardCount/);
assert.match(board, /followupDecisionPending/);
assert.match(board, /function closeFocus\(\{acknowledge=true,advanceSurface=true\}/);
assert.match(board, /only leaving that Focus may advance to follow-up questions/);
assert.doesNotMatch(board, /pendingFocusIndex==null\) maybeGenerateSurfaceFollowups/);
assert.match(board, /nextUndrawnNativeIndex\(root\)!=null\)return/);
assert.match(board, /options—not automatic follow-ups/);
assert.match(board, /Reversals/);
assert.match(board, /Repeats/);
assert.match(board, /basedOnTemplateId/);
assert.match(board, /function markQuestionEditCustom\(drawer,draft\)/);
assert.match(board, /draft\.templateId='';/);
assert.match(board, /templateSelect\.value=''/);
assert.equal((board.match(/markQuestionEditCustom\(drawer,draft\)/g) || []).length, 5, 'only the helper definition plus question-list mutations should mark a preset Custom');
assert.doesNotMatch(board, /relphiDraft(?:Pack|Stickers|Reversals|Repeats)[^\n]*markQuestionEditCustom/);
assert.doesNotMatch(board, /relphiBulkQuestions/);
assert.match(board, /<option value="">Custom<\/option>/);
assert.match(board, /const rows=labels\.length \? labels : \[''\]/);
assert.match(board, /const acceptCommaList=\(value\)=>/);
assert.match(board, /labelsList\?\.addEventListener\('paste'/);
assert.match(board, /labelsList\?\.addEventListener\('change'/);
assert.match(board, /pasted\.includes\(','\)/);
assert.match(board, /parseBulkQuestions\(pasted\)/);
assert.match(board, /draft\.labels=labels/);
assert.match(board, /templateById\(draft\.templateId \|\| draft\.basedOnTemplateId\)/);
assert.match(board, /next\.id='custom-active'/);
assert.match(board, /layout\?\.id!=='celtic-cross-10' && layout\?\.basedOn!=='celtic-cross-10'/);
assert.match(board, /function zoomExtents/);
assert.match(board, /function installPinchZoom/);
assert.match(board, /addEventListener\('touchstart',begin,\{capture:true,passive:false\}\)/);
assert.match(board, /installPinchZoom\(root\)/);
assert.match(board, /function installReadingTextArea/);
assert.match(board, /serializeDrawingBoardReading/);
assert.match(board, /relphi-copy-reading/);
assert.match(board, /function installExportArea/);
assert.match(board, /drawing-board-post-export/);
assert.match(css, /relphi-board-reading-text/);
assert.match(css, /relphi-reading-text-association/);
assert.doesNotMatch(css, /relphi-reading-text-card\.is-reversed\{[^}]*border-left/);
assert.match(app, /function drawingBoardAssociationText/);
assert.match(app, /function serializeDrawingBoardReadingText/);
assert.match(app, /drawingBoardReadingEntries/);
assert.match(app, /Relphi interpretation:/);
assert.doesNotMatch(app, /Same card, same ingredients, inverted orientation/);
assert.doesNotMatch(app, /function rowOrientationMethodText/);
assert.match(board, /renderedContentBounds\(root\)/);
assert.doesNotMatch(board, /querySelectorAll\([^\n]*card-row-item[^\n]*\)\s*\.map\([^\n]*getBoundingClientRect/);
assert.match(board, /function openFocus/);
assert.match(board, /function sacredCardSourceAt/);
assert.match(board, /Draw digital card/);
assert.match(board, /Record the card I drew/);
assert.match(board, /Continue with the shared card/);
assert.match(board, /relphiPhysicalOrientation/);
assert.match(board, /setRecordedCardOrientation/);
assert.match(board, /No matching cards in the assigned sub-pack/);
assert.match(app, /window\.RelphiTarotLedgerBridge/);
assert.match(board, /renderCardEntry/);
assert.match(board, /function installFocusSwipe/);
assert.match(board, /relphi-focus-art/);
assert.match(board, /relphi-focus-reversed-badge/);
assert.match(board, /ArrowLeft/);
assert.match(board, /ArrowRight/);
assert.match(css, /relphi-focus-main/);
assert.match(css, /relphi-board-commandbar/);
assert.match(css, /relphi-board-command-actions/);
assert.match(css, /relphi-board-settings-panel/);
assert.match(css, /relphi-settings-open[^\n]*drawing-board-board-mode/);
assert.match(css, /display:block!important/);
assert.match(chromeOwner, /const settingsBody = root\.querySelector\('\.relphi-board-settings-body'\)/);
assert.match(chromeOwner, /modeSwitch\.insertAdjacentElement\('afterend', drawer\)/);
assert.match(css, /relphi-free-settings/);
assert.match(css, /grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/);
assert.match(css, /relphi-surface-select-all/);
assert.match(css, /relphi-surface-readiness/);
assert.match(css, /relphi-surface-readiness-rail::before/);
assert.match(css, /grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/);
assert.match(css, /left:12\.5%!important;right:12\.5%!important/);
assert.match(css, /relphi-surface-readiness-step\.is-success/);
assert.match(css, /relphi-sacred-card-source/);
assert.match(css, /relphi-astrology-own-question select/);
assert.match(css, /grid-template-columns:minmax\(0,1\.6fr\) minmax\(10rem,\.8fr\)/);
assert.doesNotMatch(css, /relphi-sacred-card-source-reminder/);
assert.match(css, /relphi-attune-physical-instruction/);
assert.match(css, /relphi-attune-orientation/);
assert.match(css, /relphi-surface-keyword-builder/);
assert.match(css, /relphi-surface-keyword-matches/);
assert.match(css, /relphi-surface-composer-status/);
assert.match(css, /relphi-surface-composer-advanced>summary/);
assert.match(css, /relphi-surface-composer-advanced-body/);
assert.match(css, /data-surface-done/);
assert.match(css, /relphi-draw-options--surface>label:first-child/);
assert.match(css, /relphi-draw-options--surface>label:nth-child\(2\)::after\{content:none/);
assert.match(board, /relphiDraftReversals[^\n]*Reversals/);
assert.match(css, /relphi-focus-entry/);
assert.match(css, /relphi-focus-art\.is-reversed/);
assert.match(board, /function navigateFocus/);
assert.doesNotMatch(board, /Complete Reading/);
assert.match(board, /function drawInto/);
assert.match(board, /pendingFocusIndex/);
assert.match(board, /function setBoardOpen/);
assert.match(board, /Open Drawing Board/);
assert.match(board, /Close Drawing Board/);
assert.match(css, /touch-action:pan-x pan-y/);
assert.match(css, /relphi-is-pinching/);
assert.match(css, /data-relphi-position-id="crossing"\][^\n]*card-row-position-panel\{left:calc\(50% \+ 2\.4rem\)!important;right:auto!important;top:0!important;bottom:auto!important;[^\n]*transform:none!important/);
assert.match(css, /card-row-workspace-toolbar\.relphi-board-controller/);
assert.match(css, /relphi-reading-options-drawer/);
assert.match(css, /relphi-options-commitbar/);
assert.match(css, /relphi-focus-reader/);
assert.match(css, /card-row-workspace-toolbar:not\(\.relphi-board-controller\).*visibility:hidden!important/);
assert.match(css, /relphi-board-export/);
assert.match(css, /card-row-card \.or-card-art\.relphi-surface-face\{[^}]*aspect-ratio:auto!important[^}]*border:0!important[^}]*border-radius:0!important[^}]*clip-path:none!important/);
assert.match(sharedStyle, /site-wide tarot source-art integrity/);
assert.match(sharedStyle, /img\[src\]\[src\*="assets\/tarot\/rws\/"\][^{]*\{[^}]*border:\s*0\s*!important[^}]*border-radius:\s*0\s*!important[^}]*clip-path:\s*none\s*!important/s);
assert.match(app, /\.export-card img\{[^}]*border:0[^}]*border-radius:0[^}]*clip-path:none[^}]*object-fit:contain\}/);
assert.match(app, /\.table-art\{[^}]*border:0[^}]*border-radius:0[^}]*clip-path:none[^}]*object-fit:contain\}/);

assert.match(app, /const RELPHI_EXPORT_BRAND = Object\.freeze\(\{/);
assert.match(app, /name:'Oracle of Relphi'/);
assert.match(app, /logo:'logo\.png'/);
assert.doesNotMatch(app, /designation:'an Oracle of Relphi tool'/);
assert.match(app, /brand:\{\.\.\.RELPHI_EXPORT_BRAND\}/);
assert.match(app, /<title>Drawing Board · Oracle of Relphi<\/title>/);
assert.match(app, /class="brand-logo"/);
assert.match(app, /class="brand-wordmark">Oracle of <span>Relphi<\/span>/);
assert.match(app, /ctx\.fillText\('oracleofrelphi\.com'/);
assert.doesNotMatch(app, /Drawing Board · oracleofrelphi\.com/);
assert.doesNotMatch(app, /class="brand-tool">Drawing Board<\/div>/);
assert.doesNotMatch(app, /Drawing Board · an Oracle of Relphi tool · oracleofrelphi\.com/);
assert.equal((app.match(/drawRelphiExportBrand\(ctx,canvas,brandFooterH,brandLogoImage\)/g) || []).length,2,'both Drawing Board image exports must draw the real Oracle of Relphi logo footer');
for (const [name,source] of [['Tarot Ledger',tarotPage],['Sky Chart',skyPage],['Planetary Hours',hoursPage]]) {
  assert.match(source, /<p class="relphi-tool-brandline">an Oracle of Relphi tool<\/p>/, name + ' must identify itself as an Oracle of Relphi tool');
}
assert.match(sharedStyle, /\.relphi-tool-brandline\s*\{[^}]*color:\s*var\(--relphi-red\)/s);

console.log('Drawing Board workflow v2 checks passed.');
