const assert=require('node:assert/strict');
const fs=require('node:fs');
const workflow=fs.readFileSync('drawing-board-workflow-v2.js','utf8');
const app=fs.readFileSync('tarot-app.js','utf8');
const css=fs.readFileSync('drawing-board-workflow-v2.css','utf8');
const siteCss=fs.readFileSync('style.css','utf8');

assert.match(workflow,/\['tags','Keywords \/ Tags'\]/);
assert.match(workflow,/function keywordDraftMarkup\(draft\)/);
assert.match(workflow,/id="relphiKeywordQuery"/);
assert.match(workflow,/data-keyword-choice/);
assert.match(workflow,/RELPHI_KEYWORD_SUBPACK_CONTEXT\?\.matches/);
assert.match(workflow,/snap\.rowSelectedTags=draft\.pack==='tags'/);
assert.match(workflow,/snap\.rowTagMatchMode=draft\.keywordMatchMode==='all'/);
assert.match(app,/window\.RELPHI_KEYWORD_SUBPACK_CONTEXT = Object\.freeze/);
assert.match(app,/catalog: \(\) => canonicalTagCatalog\(\)\.slice\(\)/);
assert.match(app,/count: \(tags, mode = 'any'\)/);
assert.match(css,/relphi-keyword-builder/);
assert.match(css,/relphi-keyword-builder input\[type="search"\]/);
assert.match(css,/font-family:'Montserrat',sans-serif!important/);
assert.match(siteCss,/Relphi brand-control baseline/);
assert.match(siteCss,/button,\s*\ninput,\s*\nselect,\s*\ntextarea,\s*\noptgroup\{font-family:'Montserrat',sans-serif\}/);
console.log('Referents Pack selector exposes a branded Keywords / Tags builder and persists its selection.');
