const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const board = read('drawing-board-workflow-v2.js');
const app = read('tarot-app.js');
const css = read('drawing-board-workflow-v2.css');
const tarotPage = read('tarot.html');
const skyPage = read('sky-chart.html');
const hoursPage = read('planetaryhours.html');
const sharedStyle = read('style.css');

assert.match(board, /Native board state and rendering remain owned by tarot-app\.js/);
assert.match(app, /function renderShortList\(/);
assert.match(app, /function boardSnapshot\(/);
assert.match(board, /function beginOptionsSession/);
assert.match(board, /baseline:currentSnapshot\(\), draft:draftFromState\(\)/);
assert.match(board, /function applyOptions/);
assert.match(board, /function resetBoardFromOptions/);
assert.match(board, /function draftPrefab/);
assert.match(board, /Save template/);
assert.match(board, /Show position stickers/);
assert.match(board, /Reversals/);
assert.match(board, /Repeats/);
assert.match(board, /basedOnTemplateId/);
assert.match(board, /function markQuestionEditCustom\(drawer,draft\)/);
assert.match(board, /draft\.templateId='';/);
assert.match(board, /templateSelect\.value=''/);
assert.equal((board.match(/markQuestionEditCustom\(drawer,draft\)/g) || []).length, 5, 'only the helper definition plus question-list mutations should mark a preset Custom');
assert.doesNotMatch(board, /relphiDraft(?:Pack|Stickers|Reversals|Repeats)[^\n]*markQuestionEditCustom/);
assert.doesNotMatch(board, /relphiBulkQuestions/);
assert.match(board, /<option value="">Custom<\/option>/);
assert.match(board, /const rows=labels\.length \? labels : \[''\]/);
assert.match(board, /const acceptCommaList=\(value\)=>/);
assert.match(board, /labelsList\?\.addEventListener\('paste'/);
assert.match(board, /labelsList\?\.addEventListener\('change'/);
assert.match(board, /pasted\.includes\(','\)/);
assert.match(board, /parseBulkQuestions\(pasted\)/);
assert.match(board, /draft\.labels=labels/);
assert.match(board, /templateById\(draft\.templateId \|\| draft\.basedOnTemplateId\)/);
assert.match(board, /next\.id='custom-active'/);
assert.match(board, /layout\?\.id!=='celtic-cross-10' && layout\?\.basedOn!=='celtic-cross-10'/);
assert.match(board, /function zoomExtents/);
assert.match(board, /function installPinchZoom/);
assert.match(board, /addEventListener\('touchstart',begin,\{capture:true,passive:false\}\)/);
assert.match(board, /installPinchZoom\(root\)/);
assert.match(board, /function installReadingTextArea/);
assert.match(board, /serializeDrawingBoardReading/);
assert.match(board, /relphi-copy-reading/);
assert.match(board, /function installExportArea/);
assert.match(board, /drawing-board-post-export/);
assert.match(css, /relphi-board-reading-text/);
assert.match(css, /relphi-reading-text-association/);
assert.doesNotMatch(css, /relphi-reading-text-card\.is-reversed\{[^}]*border-left/);
assert.match(app, /function drawingBoardAssociationText/);
assert.match(app, /function serializeDrawingBoardReadingText/);
assert.match(app, /drawingBoardReadingEntries/);
assert.match(app, /Relphi interpretation:/);
assert.doesNotMatch(app, /Same card, same ingredients, inverted orientation/);
assert.doesNotMatch(app, /function rowOrientationMethodText/);
assert.match(board, /stateContentBounds\(snapshot,count\)/);
assert.doesNotMatch(board, /querySelectorAll\([^\n]*card-row-item[^\n]*\)\s*\.map\([^\n]*getBoundingClientRect/);
assert.match(board, /function openFocus/);
assert.match(app, /window\.RelphiTarotLedgerBridge/);
assert.match(board, /renderCardEntry/);
assert.match(board, /function installFocusSwipe/);
assert.match(board, /relphi-focus-art/);
assert.match(board, /relphi-focus-reversed-badge/);
assert.match(board, /ArrowLeft/);
assert.match(board, /ArrowRight/);
assert.match(css, /relphi-focus-main/);
assert.match(css, /relphi-focus-entry/);
assert.match(css, /relphi-focus-art\.is-reversed/);
assert.match(board, /function navigateFocus/);
assert.doesNotMatch(board, /Complete Reading/);
assert.match(board, /function drawInto/);
assert.match(board, /pendingFocusIndex/);
assert.match(board, /function setBoardOpen/);
assert.match(board, /Open Drawing Board/);
assert.match(board, /Close Drawing Board/);
assert.match(css, /touch-action:pan-x pan-y/);
assert.match(css, /relphi-is-pinching/);
assert.match(css, /data-relphi-position-id="crossing"\][^\n]*card-row-position-panel\{left:calc\(50% \+ 2\.4rem\)!important;right:auto!important;top:0!important;bottom:auto!important;[^\n]*transform:none!important/);
assert.match(css, /card-row-workspace-toolbar\.relphi-board-controller/);
assert.match(css, /relphi-reading-options-drawer/);
assert.match(css, /relphi-options-commitbar/);
assert.match(css, /relphi-focus-reader/);
assert.match(css, /card-row-workspace-toolbar:not\(\.relphi-board-controller\).*visibility:hidden!important/);
assert.match(css, /relphi-board-export/);
assert.match(css, /card-row-card \.or-card-art\.relphi-surface-face\{[^}]*aspect-ratio:500\/866!important/);

assert.match(app, /const RELPHI_EXPORT_BRAND = Object\.freeze\(\{/);
assert.match(app, /name:'Oracle of Relphi'/);
assert.match(app, /designation:'an Oracle of Relphi tool'/);
assert.match(app, /brand:\{\.\.\.RELPHI_EXPORT_BRAND\}/);
assert.match(app, /<title>Drawing Board · Oracle of Relphi<\/title>/);
assert.match(app, /Created with <strong>Oracle of Relphi<\/strong>/);
assert.match(app, /Drawing Board · an Oracle of Relphi tool · oracleofrelphi\.com/);
assert.equal((app.match(/drawRelphiExportBrand\(ctx,canvas,brandFooterH\)/g) || []).length,2,'both Drawing Board image exports must carry the Oracle of Relphi footer');
for (const [name,source] of [['Tarot Ledger',tarotPage],['Sky Chart',skyPage],['Planetary Hours',hoursPage]]) {
  assert.match(source, /<p class="relphi-tool-brandline">an Oracle of Relphi tool<\/p>/, name + ' must identify itself as an Oracle of Relphi tool');
}
assert.match(sharedStyle, /\.relphi-tool-brandline\s*\{/);

console.log('Drawing Board workflow v2 checks passed.');
