import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { createRequire } from 'node:module';

import { auditSvg, intake, IntakeError } from '../tools/intake-canonical-glyph-source.mjs';

const require=createRequire(import.meta.url);
const sharp=require('sharp');

const root=path.resolve(import.meta.dirname,'..');
const fixture=name=>path.join(root,'tests/fixtures/canonical-intake',name);
const manifest=path.join(root,'assets/canonical-glyphs/v1/manifest.json');
const temp=()=>mkdtemp(path.join(os.tmpdir(),'canonical-intake-'));
const sha256=value=>createHash('sha256').update(value).digest('hex');
async function expectCode(promise,code){await assert.rejects(promise,error=>error instanceof IntakeError&&error.code===code);}

test('valid path-only master produces review-only evidence and derived path',async()=>{const out=await temp();try{const report=await intake({manifestPath:manifest,submissions:[{identity:'chiron',file:fixture('valid-path.svg')}],outputDirectory:out});assert.equal(report.production_package_modified,false);assert.equal(report.submissions[0].required_final_path,'assets/canonical-glyphs/v1/masters/assets/planet-glyphs/chiron.svg');assert.equal(report.submissions[0].externally_approved,false);assert.match(report.submissions[0].decision_required,/Approve or reject/);}finally{await rm(out,{recursive:true,force:true});}});
test('valid basic-shape master passes',()=>assert.doesNotThrow(()=>auditSvg(requireText('valid-basic-shapes.svg'))));
test('existing Circled overlay passes unchanged with backplate declaration',async()=>{const out=await temp();try{const report=await intake({manifestPath:manifest,submissions:[{overlay:'circled',file:path.join(root,'assets/canonical-glyphs/v1/overlays/circled.svg'),zOrder:'backplate'}],outputDirectory:out,replacementReview:true});assert.equal(report.submissions[0].source_audit.raw_sha256,'d168391cea9c0d662209221f34cdf39e43b1eddc8f3fb3a350b10ec5bc8e0f06');}finally{await rm(out,{recursive:true,force:true});}});
function requireText(name){return fs.readFileSync(fixture(name),'utf8');}
for(const [name,code] of [['wrong-viewbox.svg','WRONG_VIEWBOX'],['text-font.svg','FORBIDDEN_ELEMENT'],['transform.svg','TRANSFORM_PROHIBITED'],['clipping.svg','FORBIDDEN_ELEMENT'],['external-image.svg','FORBIDDEN_ELEMENT'],['script.svg','FORBIDDEN_ELEMENT'],['use-symbol.svg','FORBIDDEN_ELEMENT'],['empty.svg','EMPTY_ARTWORK'],['malformed.svg','MALFORMED_SVG'],['identical-prohibited.svg','TRANSFORM_PROHIBITED']])test(`${name} fails closed`,()=>assert.throws(()=>auditSvg(requireText(name)),error=>error.code===code));
test('duplicate identity path fails',async()=>{const out=await temp();try{await expectCode(intake({manifestPath:manifest,submissions:[{identity:'chiron',file:fixture('valid-path.svg')},{identity:'chiron',file:fixture('valid-path.svg')}],outputDirectory:out}),'DUPLICATE_IDENTITY_PATH');}finally{await rm(out,{recursive:true,force:true});}});
test('undeclared shared geometry fails across identities',async()=>{const out=await temp();try{const copy=path.join(out,'vertex.svg');await writeFile(copy,(await readFile(fixture('valid-path.svg'),'utf8')).replace('Chiron','Vertex'));await expectCode(intake({manifestPath:manifest,submissions:[{identity:'chiron',file:fixture('valid-path.svg')},{identity:'vertex',file:copy}],outputDirectory:out}),'UNDECLARED_SHARED_GEOMETRY');}finally{await rm(out,{recursive:true,force:true});}});
test('mismatched accessibility identity fails',async()=>{const out=await temp();try{await expectCode(intake({manifestPath:manifest,submissions:[{identity:'chiron',file:fixture('mismatched-identity.svg')}],outputDirectory:out}),'MISMATCHED_IDENTITY');}finally{await rm(out,{recursive:true,force:true});}});
test('missing raster reference fails',async()=>{const out=await temp();try{await expectCode(intake({manifestPath:manifest,submissions:[{identity:'chiron',file:fixture('valid-path.svg'),reference:path.join(out,'missing.png')}],outputDirectory:out}),'REFERENCE_MISSING');}finally{await rm(out,{recursive:true,force:true});}});
test('raster difference remains evidence and never approval',async()=>{const out=await temp();try{const ref=path.join(out,'ref.png');await sharp({create:{width:200,height:200,channels:4,background:{r:255,g:255,b:255,alpha:0}}}).png().toFile(ref);const report=await intake({manifestPath:manifest,submissions:[{identity:'chiron',file:fixture('raster-different.svg'),reference:ref}],outputDirectory:out});assert.equal(report.submissions[0].raster_comparisons.length,6);assert.ok(report.submissions[0].raster_comparisons.every(x=>x.differing_pixels>0));assert.equal(report.submissions[0].externally_approved,false);}finally{await rm(out,{recursive:true,force:true});}});
test('available identity requires explicit replacement review',async()=>{const out=await temp();try{await expectCode(intake({manifestPath:manifest,submissions:[{identity:'mercury',file:path.join(root,'assets/canonical-glyphs/v1/masters/assets/planet-glyphs/mercury.svg')}],outputDirectory:out}),'IDENTITY_NOT_BLOCKED');}finally{await rm(out,{recursive:true,force:true});}});
test('matching hashes alone do not constitute external approval',async()=>{const out=await temp();try{const approval=path.join(out,'approval.json');const source=await readFile(fixture('valid-path.svg'));const manifestSource=await readFile(manifest);await writeFile(approval,JSON.stringify({candidate_sha256:sha256(source),source_path:'assets/canonical-glyphs/v1/masters/assets/planet-glyphs/chiron.svg',reference_package_hash:sha256(manifestSource)}));await expectCode(intake({manifestPath:manifest,submissions:[{identity:'chiron',file:fixture('valid-path.svg')}],outputDirectory:out,approvalRecord:approval}),'INVALID_EXTERNAL_APPROVAL');}finally{await rm(out,{recursive:true,force:true});}});
test('complete package-bound external approval is reported but never auto-installed',async()=>{const out=await temp();try{const approval=path.join(out,'approval.json');const source=await readFile(fixture('valid-path.svg'));const manifestSource=await readFile(manifest);await writeFile(approval,JSON.stringify({record_type:'master-approval',identity:'chiron',candidate_sha256:sha256(source),source_path:'assets/canonical-glyphs/v1/masters/assets/planet-glyphs/chiron.svg',approving_authority:'external-reviewer',approval_date:'2026-08-06',baseline_commit:'c244f81f2149b37267f4290664b0db32de1c5ec9',reference_package_hash:sha256(manifestSource),decision_type:'approve-new-static-master',notes:'Test fixture approval.',geometry_confirmation:{geometry:true,whitespace:true,scale:true,position:true,proportions:true,strokes:true},no_fallback_or_runtime_fitting_authorized:true,signature:{algorithm:'test-only',key_id:'fixture',signed_payload_sha256:'0'.repeat(64),value:'fixture-signature'}}));const report=await intake({manifestPath:manifest,submissions:[{identity:'chiron',file:fixture('valid-path.svg')}],outputDirectory:out,approvalRecord:approval});assert.equal(report.production_package_modified,false);assert.equal(report.submissions[0].externally_approved,true);assert.equal(report.submissions[0].approval_status,'external-record-present-review-still-required');}finally{await rm(out,{recursive:true,force:true});}});
