const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const builder = read('sky-chart-builder-v4.js');
const page = read('sky-chart.html');
const app = read('tarot-app.js');
const nav = read('navloader.js');
const menu = read('menu.js');
const tarotDateBridge = read('tarot-date-sky-bridge-v1.js');
const planetaryHours = read('planetaryhours.html');

assert.match(builder, /skyA:'relphiSkyChartA', skyB:'relphiSkyChartB'/, 'V4 must use isolated SkyChart slots.');
assert.doesNotMatch(builder, /skyA:'relphiTarotChart'/, 'V4 must not use the Tarot ledger as Sky A storage.');
assert.match(builder, /data-action="placements"/, 'The wizard must expose one placement-entry path.');
assert.match(builder, /relphi-v4-combobox/, 'The name and saved-sky picker must be one combobox.');
assert.match(builder, /data-load-name/, 'Saved skies must load directly from the name dropdown.');
assert.match(builder, /nameConflictA/, 'Typing a duplicate name must open an explicit conflict choice.');
assert.match(builder, /nextAvailableName/, 'Duplicate names must receive a computer-style numeric suffix.');
assert.match(builder, /Type, paste, or build placements/, 'The unified placement editor heading is missing.');
assert.match(builder, /relphiLiveSync/, 'Field-to-text live synchronization is missing.');
assert.match(builder, /const editingExisting = hasPlacements/, 'Back from editing an existing sky must return to the completed panels.');
assert.match(builder, /state\.step = slot === 'skyA' \? 'methodA' : 'methodB'/, 'Edit must return to the choice between placements and calculation.');
assert.match(builder, /Change the date, time, place, or house system and recalculate/, 'The edit path must explain that calculation metadata can be changed.');
assert.match(builder, /setValue\('skyCalcDateTime', profile\.dateTime \|\| '', false\)/, 'Editing a calculated sky must restore its date and time.');
assert.match(builder, /state\.pendingName = input\?\.value\.trim\(\) \|\| ''/, 'A blank optional name must remain blank until the sky date is known.');
assert.match(builder, /'Unnamed sky · ' \+ date/, 'Unnamed calculated skies must use their actual sky date.');
assert.match(builder, /Promise\.resolve\(payload\)/, 'Saved skies must load from their authoritative library payload without waiting on unrelated slot persistence.');
assert.match(builder, /state\.step = hasPlacements\(state\.skyB\) \? 'completeBoth' : 'completeA'/, 'Editing Sky A must preserve an existing Sky B comparison.');
assert.match(builder, /data-action="quick-now"/, 'The name screen must offer a one-click Now sky action.');
assert.match(builder, /Use the present moment and your current location\. No name required\./, 'The Now action must explain that naming is unnecessary.');
assert.match(builder, /state\.pendingName = ''[\s\S]*setTimeout\(runHereNow, 0\)/, 'The Now action must bypass naming and run the current time/location calculation.');
assert.match(builder, /toLowerCase\(\) === 'now' \? '' : requestedName/, 'A legacy Now handoff must not become a sky name.');
assert.match(builder, /data-action="quick-birth"/, 'The quick choices must include My birth chart.');
assert.match(builder, /Create a new sky/, 'The opening screen must clearly identify the primary new-sky path.');
assert.match(builder, /value=""/, 'A fresh new-sky field must not inherit the name of a saved sky.');
assert.match(builder, /data-form-type="other"[\s\S]*readonly/, 'The fresh name field must resist browser autofill until the user chooses to type.');
assert.match(builder, /freshNameInput\.value = ''[\s\S]*freshNameInput\.readOnly = false/, 'The name field must be blank when it is intentionally activated.');
assert.match(builder, /autofillGuard = setInterval[\s\S]*if \(!nameClaimed\) freshNameInput\.value = ''/, 'Delayed browser autofill must not repopulate a new sky name.');
assert.match(builder, /Set up My birth chart/, 'The birth-chart quick action must explain its one-time setup purpose.');
assert.match(builder, /state\.quickPurpose === 'birth' \? 'My birth chart'/, 'Birth-chart setup must save under its stable quick-action name without asking the user to name it.');
assert.match(builder, /clear === 'skyA' && hasPlacements\(state\.skyB\)/, 'Clearing Sky A must detect an occupied Sky B.');
assert.match(builder, /state\.skyA = state\.skyB[\s\S]*removeJson\(SLOT_KEYS\.skyB\)/, 'Clearing Sky A must promote Sky B into Sky A and remove only the old B slot.');
assert.match(builder, /function calculationProfileFromFields\(payload\)/, 'Calculated skies must retain their entered local date/time profile.');
assert.match(builder, /function recoverCalculationProfile\(payload\)/, 'Older calculated skies must recover local time from their saved instant and time zone.');
assert.match(builder, /skyCreatorSaveWizard/, 'The placement editor must commit through the native engine.');
assert.match(builder, /skyCalcStatus/, 'The wizard must detect completion from the native Astronomy Engine status.');
assert.match(page, /id="skyFoundationRoot"/, 'The current Sky Chart foundation root is missing.');
assert.match(page, /relphi-glyph-masters-v1\.js\?v=1/, 'The immutable glyph masters must load on Sky Chart.');
assert.match(page, /relphi-glyph-registry-v1\.js\?v=1/, 'The semantic glyph registry must load on Sky Chart.');
assert.match(page, /relphi-glyph-component-v1\.js\?v=5/, 'The strict canonical glyph component must load on Sky Chart.');
assert.match(builder, /function syncNativeSlots\(a, b\)/, 'The wizard must hydrate both native renderer slots atomically.');
assert.match(builder, /byId\('loadChart'\)\?\.click\(\)/, 'Sky A must be loaded into the native relationship renderer.');
assert.match(builder, /byId\('loadCurrentSky'\)\?\.click\(\)/, 'Sky B must be loaded into the native relationship renderer.');
assert.match(page, /astronomy\.browser\.min\.js/, 'The Astronomy Engine is not loaded.');
assert.match(app, /function decanCardFor\(/, 'Decan-to-card correspondence is missing.');
assert.match(app, /function renderUnifiedChartResults\(/, 'Tarot card result rendering is missing.');
assert.match(app, /function syncSkyPasteFromPlacements\(/, 'Placement-to-text synchronization is missing.');
assert.match(app, /const enteredTimeZone = \$\('skyCalcTimeZone'\)/, 'The calculator must use the entered time zone for its immediate local path.');
assert.doesNotMatch(app, /const resolved = await enrichSkyCalcFromCoordinates\(\{ forceLocation:true, forceTimeZone:true, requireTimeZone:false \}\)/, 'The calculator must not block every run on forced location enrichment.');
assert.match(builder, /function runAfterLocationSearch\(\)/, 'Calculate must wait for a typed location to resolve before using its coordinates.');
assert.match(builder, /foundLatitude && foundLongitude[\s\S]*byId\('skyCalcRun'\)\?\.click\(\)/, 'The deferred calculation must run only after both coordinates are present.');
assert.doesNotMatch(builder, /\|Location \|/, 'A successful Location found message must not cancel the calculation watcher.');
assert.match(builder, /input\.addEventListener\('focus',[\s\S]*input\.select\(\)/, 'Focusing the location field must make its existing text easy to replace.');
assert.match(builder, /\['skyCalcLocation','skyCalcLatitude','skyCalcLongitude','skyCalcTimeZone'\]/, 'Clearing a location must also clear its stale coordinate and time-zone data.');
assert.match(builder, /function applyExternalHandoff\(\)/, 'SkyChart must consume Tarot and Planetary Hours date/time/place handoffs.');
assert.match(builder, /const calculateImmediately = externalHandoff\.autoRun && externalHandoff\.latitude && externalHandoff\.longitude/, 'A complete Planetary Hours packet must calculate immediately.');
assert.match(builder, /if \(calculateImmediately\) \{ closeCalculator\(\); setNativeTarget\(state\.editingSlot\); \}/, 'Automatic Planetary Hours calculations must keep the calculator closed.');
assert.match(builder, /setTimeout\(function \(\) \{ byId\('skyCalcRun'\)\?\.click\(\); \}, 0\)/, 'The complete handoff must run without another user action.');
assert.match(builder, /\['datetime','date','lat','lon','tz','loc','name','calc','source'\]/, 'Consumed handoff parameters must be removed before the legacy loader runs.');
assert.match(planetaryHours, /preview: 'pr55'/, 'Planetary Hours must open the current SkyChart wizard.');
assert.match(planetaryHours, /source: 'planetary-hours'/, 'Planetary Hours must identify its SkyChart handoff.');
assert.match(planetaryHours, /<a class="ph-current-wheel-card" id="phCurrentWheelCard"/, 'The full current-placement wheel card must be an accessible link.');
assert.match(planetaryHours, /el\.dateFieldLink\.href = skyChartHref;[\s\S]*el\.phCurrentWheelCard\.href = skyChartHref;/, 'The button and full wheel card must always share the exact same Sky Chart handoff URL.');
assert.match(planetaryHours, /navloader\.js\?v=49/, 'Planetary Hours must load the corrected shared navigation controller.');
assert.match(menu, /__relphiMenuControllerInstalled/, 'The navigation controller must guard against duplicate initialization.');
assert.match(menu, /event\.target\.closest\('\.menu-container \.logo-btn, \.menu-container #menuButton'\)/, 'The logo must use one delegated click controller.');
assert.doesNotMatch(menu, /button\.addEventListener\('click'/, 'The logo must not also receive a second per-button click listener.');
assert.match(tarotDateBridge, /date \+ 'T12:00'/, 'Tarot date entry must create its date sky at an explicit local-noon default.');
assert.match(tarotDateBridge, /relphiPlanetaryHoursWhereWhen/, 'Tarot date skies must reuse the saved location and time-zone packet.');
assert.match(tarotDateBridge, /byId\('saveChart'\)\?\.click\(\)/, 'Tarot date skies must save only through the Tarot Ledger chart bridge.');
assert.match(builder, /String\(minute\)\.padStart\(2, '0'\) \+ '′'/, 'Completed Sky panels must show placement minutes.');
assert.match(nav, /menu\.js\?v=6/, 'The single-toggle menu controller must be cache-busted.');
assert.match(nav, /sky-chart-builder-v4\.js\?v=18/, 'The direct-handoff Sky Builder must be cache-busted.');
assert.match(nav, /function loadSkyBuilder\(attempt\)/, 'The Sky Builder loader must recover from a failed asset request.');
assert.match(nav, /function waitForSkyBuilder\(started, onTimeout\)/, 'The loader must wait for builder installation, not merely script download.');
assert.match(nav, /Date\.now\(\) - started < 8000/, 'The readiness wait must be bounded.');
assert.match(builder, /relphi:sky-builder-ready/, 'The builder must announce that installation is complete.');
assert.match(builder, /byId\('relphiPreviewLoadFailure'\)\?\.remove\(\)/, 'A late builder install must remove a stale failure notice.');
assert.match(nav, /retry < 2/, 'The Sky Builder loader must retry before showing its failure message.');
assert.match(nav, /failed\.remove\(\)/, 'A failed builder script must be removed before retrying with a fresh cache key.');
assert.match(page, /navloader\.js\?v=53/, 'The current navigation controller must be cache-busted on Sky Chart.');

console.log('SkyChart V4 engine, Tarot, storage, calculator, and synchronized-editor checks passed.');
