const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const builder = read('sky-chart-builder-v4.js');
const page = read('sky-chart.html');
const app = read('tarot-app.js');
const nav = read('navloader.js');
const signCusps = read('sky-chart-sign-cusps-v1.js');
const glyphStyle = read('sky-chart-ph-glyph-style-v1.js');
const tarotDateBridge = read('tarot-date-sky-bridge-v1.js');
const planetaryHours = read('planetaryhours.html');

assert.match(builder, /skyA:'relphiSkyChartA', skyB:'relphiSkyChartB'/, 'V4 must use isolated SkyChart slots.');
assert.doesNotMatch(builder, /skyA:'relphiTarotChart'/, 'V4 must not use the Tarot ledger as Sky A storage.');
assert.match(builder, /data-action="placements"/, 'The wizard must expose one placement-entry path.');
assert.match(builder, /relphi-v4-combobox/, 'The name and saved-sky picker must be one combobox.');
assert.match(builder, /data-load-name/, 'Saved skies must load directly from the name dropdown.');
assert.match(builder, /nameConflictA/, 'Typing a duplicate name must open an explicit conflict choice.');
assert.match(builder, /nextAvailableName/, 'Duplicate names must receive a computer-style numeric suffix.');
assert.match(builder, /Type, paste, or build placements/, 'The unified placement editor heading is missing.');
assert.match(builder, /relphiLiveSync/, 'Field-to-text live synchronization is missing.');
assert.match(builder, /const editingExisting = hasPlacements/, 'Back from editing an existing sky must return to the completed panels.');
assert.match(builder, /function calculationProfileFromFields\(payload\)/, 'Calculated skies must retain their entered local date/time profile.');
assert.match(builder, /function recoverCalculationProfile\(payload\)/, 'Older calculated skies must recover local time from their saved instant and time zone.');
assert.match(builder, /skyCreatorSaveWizard/, 'The placement editor must commit through the native engine.');
assert.match(builder, /skyCalcStatus/, 'The wizard must detect completion from the native Astronomy Engine status.');
assert.match(page, /id="saveChart"[^>]*hidden/, 'The native Sky A bridge is missing.');
assert.match(page, /id="saveCurrentSky"[^>]*hidden/, 'The native Sky B bridge is missing.');
assert.match(page, /id="loadChart"[^>]*hidden/, 'The native Sky A hydration bridge is missing.');
assert.match(page, /id="loadCurrentSky"[^>]*hidden/, 'The native Sky B hydration bridge is missing.');
assert.match(builder, /function syncNativeSlots\(a, b\)/, 'The wizard must hydrate both native renderer slots atomically.');
assert.match(builder, /byId\('loadChart'\)\?\.click\(\)/, 'Sky A must be loaded into the native relationship renderer.');
assert.match(builder, /byId\('loadCurrentSky'\)\?\.click\(\)/, 'Sky B must be loaded into the native relationship renderer.');
assert.match(page, /id="skyCalcNow"/, 'The calculator must retain Use now.');
assert.match(page, /id="skyCalcGeo"/, 'The calculator must retain Use Here.');
assert.match(page, /astronomy\.browser\.min\.js/, 'The Astronomy Engine is not loaded.');
assert.match(page, /tarot-cards\.js/, 'Tarot correspondence data is not loaded.');
assert.match(app, /function decanCardFor\(/, 'Decan-to-card correspondence is missing.');
assert.match(app, /function renderUnifiedChartResults\(/, 'Tarot card result rendering is missing.');
assert.match(app, /function syncSkyPasteFromPlacements\(/, 'Placement-to-text synchronization is missing.');
assert.match(app, /const enteredTimeZone = \$\('skyCalcTimeZone'\)/, 'The calculator must use the entered time zone for its immediate local path.');
assert.doesNotMatch(app, /const resolved = await enrichSkyCalcFromCoordinates\(\{ forceLocation:true, forceTimeZone:true, requireTimeZone:false \}\)/, 'The calculator must not block every run on forced location enrichment.');
assert.match(nav, /sky-chart-sign-cusps-v1\.js/, 'The full sign-cusp overlay must load on SkyChart.');
assert.match(signCusps, /index < 6/, 'Sign boundaries must be drawn as six full diameters.');
assert.match(signCusps, /relphi-sign-cusp-marker/, 'Sign cusp edge markers are missing.');
assert.match(builder, /function applyExternalHandoff\(\)/, 'SkyChart must consume Tarot and Planetary Hours date/time/place handoffs.');
assert.match(builder, /\['datetime','date','lat','lon','tz','loc','name','calc','source'\]/, 'Consumed handoff parameters must be removed before the legacy loader runs.');
assert.match(planetaryHours, /preview: 'pr55'/, 'Planetary Hours must open the current SkyChart wizard.');
assert.match(planetaryHours, /source: 'planetary-hours'/, 'Planetary Hours must identify its SkyChart handoff.');
assert.match(tarotDateBridge, /date \+ 'T12:00'/, 'Tarot date entry must create its date sky at an explicit local-noon default.');
assert.match(tarotDateBridge, /relphiPlanetaryHoursWhereWhen/, 'Tarot date skies must reuse the saved location and time-zone packet.');
assert.match(tarotDateBridge, /byId\('saveChart'\)\?\.click\(\)/, 'Tarot date skies must save only through the Tarot Ledger chart bridge.');
assert.match(glyphStyle, /Planetary Hours mini zodiac wheel/, 'Comparison marker styling must document its Planetary Hours source.');
assert.match(glyphStyle, /chart-wheel-stick-knob/, 'Comparison wheel marker discs must match the Planetary Hours treatment.');
assert.match(glyphStyle, /r:10\.5px!important/, 'Comparison placement circles must be large enough to read.');
assert.match(glyphStyle, /font-size:13px!important/, 'Comparison placement glyphs must be large enough to read.');
assert.match(builder, /String\(minute\)\.padStart\(2, '0'\) \+ '′'/, 'Completed Sky panels must show placement minutes.');
assert.match(nav, /sky-chart-ph-glyph-style-v1\.js\?v=2/, 'The larger glyph stylesheet must be cache-busted.');
assert.match(nav, /sky-chart-builder-v4\.js\?v=9/, 'The minute-aware Sky panel must be cache-busted.');

console.log('SkyChart V4 engine, Tarot, storage, calculator, and synchronized-editor checks passed.');
