from pathlib import Path
p=Path('tests/drawing-board-runtime.test.js')
text=p.read_text()
old="""  const desktopFocus=await desktop.evaluate(()=>{\n    const art=document.querySelector('.relphi-focus-art')?.getBoundingClientRect();\n    const entry=document.querySelector('.relphi-focus-entry')?.getBoundingClientRect();\n    const pane=document.querySelector('.relphi-focus-art-pane')?.getBoundingClientRect();\n    return art&&entry&&pane?{sideBySide:art.right<=entry.left+3,entryText:document.querySelector('.relphi-focus-entry')?.textContent?.trim().length||0,artContained:art.top>=pane.top-2&&art.bottom<=pane.bottom+2&&art.left>=pane.left-2&&art.right<=pane.right+2}:null;\n  });\n"""
new="""  const desktopFocus=await desktop.evaluate(()=>{\n    const artEl=document.querySelector('.relphi-focus-art');\n    const art=artEl?.getBoundingClientRect();\n    const entry=document.querySelector('.relphi-focus-entry')?.getBoundingClientRect();\n    const paneEl=document.querySelector('.relphi-focus-art-pane');\n    const pane=paneEl?.getBoundingClientRect();\n    if (!artEl || !art || !entry || !pane) return null;\n    const nw=artEl.naturalWidth||1, nh=artEl.naturalHeight||1;\n    const scale=Math.min(art.width/nw,art.height/nh);\n    const renderedW=nw*scale, renderedH=nh*scale;\n    const rendered={left:art.left+(art.width-renderedW)/2,right:art.left+(art.width+renderedW)/2,top:art.top+(art.height-renderedH)/2,bottom:art.top+(art.height+renderedH)/2};\n    return {\n      sideBySide:art.right<=entry.left+3,\n      entryText:document.querySelector('.relphi-focus-entry')?.textContent?.trim().length||0,\n      objectFit:getComputedStyle(artEl).objectFit,\n      paneOverflow:getComputedStyle(paneEl).overflow,\n      artContained:rendered.top>=pane.top-2&&rendered.bottom<=pane.bottom+2&&rendered.left>=pane.left-2&&rendered.right<=pane.right+2,\n      rendered,pane:{left:pane.left,right:pane.right,top:pane.top,bottom:pane.bottom}\n    };\n  });\n"""
if old not in text:
    raise SystemExit('desktop focus geometry block not found')
text=text.replace(old,new,1)
old2="""  assert.ok(desktopFocus?.sideBySide,'desktop focus view must show full art beside the Ledger entry: '+JSON.stringify(desktopFocus));\n  assert.ok(desktopFocus?.artContained,'desktop focus view must contain the entire card art above the film strip: '+JSON.stringify(desktopFocus));\n  assert.ok(desktopFocus.entryText>100,'desktop focus view must show the full Ledger entry');\n"""
new2="""  assert.ok(desktopFocus?.sideBySide,'desktop focus view must show full art beside the Ledger entry: '+JSON.stringify(desktopFocus));\n  assert.equal(desktopFocus?.objectFit,'contain','desktop focus art must use contain rather than crop');\n  assert.equal(desktopFocus?.paneOverflow,'hidden','desktop focus art pane must clip its viewport boundary');\n  assert.ok(desktopFocus?.artContained,'desktop focus view must contain the entire rendered card art above the film strip: '+JSON.stringify(desktopFocus));\n  assert.ok(desktopFocus.entryText>100,'desktop focus view must show the full Ledger entry');\n"""
if old2 not in text:
    raise SystemExit('desktop focus assertion block not found')
p.write_text(text.replace(old2,new2,1))
